<?php
$status = array(
			array(
				'COD_TIPO_SITU' => 'C',
				'COD_SITU'      => '1',
				'NOM_SITUACION' => 'EN REPARTO CONFIRMADO',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'C',
				'COD_SITU'      => '2',
				'NOM_SITUACION' => 'EN REPARTO CONFIRMADO STR',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'C',
				'COD_SITU'      => '3',
				'NOM_SITUACION' => 'EN REPARTO CONFIRMADO - BULTOS',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'C',
				'COD_SITU'      => '4',
				'NOM_SITUACION' => 'EN REPARTO CONFIRMADO  OTROS',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'C',
				'COD_SITU'      => '5',
				'NOM_SITUACION' => 'EN REPARTO CONFIRMADO OMR',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'C',
				'COD_SITU'      => '6',
				'NOM_SITUACION' => 'EN RPTO CONFIRMAD POR RELACION',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'C',
				'COD_SITU'      => '101',
				'NOM_SITUACION' => 'Salio de reparto a una ISLA',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'C',
				'COD_SITU'      => '845',
				'NOM_SITUACION' => 'FINAL DE RETENCION',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'C',
				'COD_SITU'      => '860',
				'NOM_SITUACION' => 'EN REPARTO INTERNACIONAL',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'D',
				'COD_SITU'      => '223',
				'NOM_SITUACION' => 'MERCANCIA DISPONIBLE REPARTO',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'D',
				'COD_SITU'      => '846',
				'NOM_SITUACION' => 'SALE DE ADUANAS',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '308',
				'NOM_SITUACION' => 'MERCANCIA EN N.T. ZAL',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '310',
				'NOM_SITUACION' => 'MERCANCIA EN N.T. NAVALMORAL',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '313',
				'NOM_SITUACION' => 'MERCANCIA EN N.T. MANZANARES',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '314',
				'NOM_SITUACION' => 'MERCANCIA EN N.T. CORDOBA',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '323',
				'NOM_SITUACION' => 'MERCANCIA EN N.T. JAEN',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '328',
				'NOM_SITUACION' => 'MERCANCIA EN N.T. CENTRAL',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '329',
				'NOM_SITUACION' => 'MERCANCIA EN N.T. ANTEQUERA',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '335',
				'NOM_SITUACION' => 'MERCANCIA EN N.T. LAS PALMAS',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '346',
				'NOM_SITUACION' => 'MERCANCIA EN N.T. VALENCIA',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '349',
				'NOM_SITUACION' => 'MERCANCIA EN N.T. BENAVENTE',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '350',
				'NOM_SITUACION' => 'MERCANCIA EN N.T. ZARAGOZA',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '364',
				'NOM_SITUACION' => 'MERCANCIA EN N.T. MERIDA',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '367',
				'NOM_SITUACION' => 'MERCANCIA EN N.T. MIRANDA',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '368',
				'NOM_SITUACION' => 'MERCANCIA EN N.T. PONFERRADA',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '388',
				'NOM_SITUACION' => 'MERCANCIA EN N.T. EL PRAT',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '399',
				'NOM_SITUACION' => 'MERCANCIA EN PLAT. MANZANARES',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '401',
				'NOM_SITUACION' => 'MERCANCIA EN VITORIA',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '402',
				'NOM_SITUACION' => 'MERCANCIA EN ALBACETE',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '403',
				'NOM_SITUACION' => 'MERCANCIA EN ALICANTE',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '404',
				'NOM_SITUACION' => 'MERCANCIA EN ALMERIA',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '405',
				'NOM_SITUACION' => 'MERCANCIA EN AVILA',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '406',
				'NOM_SITUACION' => 'MERCANCIA EN BADAJOZ',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '407',
				'NOM_SITUACION' => 'MERCANCIA EN MALLORCA',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '408',
				'NOM_SITUACION' => 'MERCANCIA EN BARCELONA',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '409',
				'NOM_SITUACION' => 'MERCANCIA EN BURGOS',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '410',
				'NOM_SITUACION' => 'MERCANCIA EN CACERES',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '411',
				'NOM_SITUACION' => 'MERCANCIA EN CADIZ',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '412',
				'NOM_SITUACION' => 'MERCANCIA EN CASTELLON',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '413',
				'NOM_SITUACION' => 'MERCANCIA EN CIUDAD REAL',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '414',
				'NOM_SITUACION' => 'MERCANCIA EN CORDOBA',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '415',
				'NOM_SITUACION' => 'MERCANCIA EN LA CORUNA',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '416',
				'NOM_SITUACION' => 'MERCANCIA EN CUENCA',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '417',
				'NOM_SITUACION' => 'MERCANCIA EN GERONA',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '418',
				'NOM_SITUACION' => 'MERCANCIA EN GRANADA',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '419',
				'NOM_SITUACION' => 'MERCANCIA EN GUADALAJARA',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '420',
				'NOM_SITUACION' => 'MERCANCIA EN SAN SEBASTIAN',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '421',
				'NOM_SITUACION' => 'MERCANCIA EN HUELVA',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '422',
				'NOM_SITUACION' => 'MERCANCIA EN HUESCA',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '423',
				'NOM_SITUACION' => 'MERCANCIA EN JAEN',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '424',
				'NOM_SITUACION' => 'MERCANCIA EN LEON',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '425',
				'NOM_SITUACION' => 'MERCANCIA EN LLEIDA',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '426',
				'NOM_SITUACION' => 'MERCANCIA EN LOGRONO',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '427',
				'NOM_SITUACION' => 'MERCANCIA EN LUGO',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '428',
				'NOM_SITUACION' => 'MERCANCIA EN MADRID',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '429',
				'NOM_SITUACION' => 'MERCANCIA EN MALAGA',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '430',
				'NOM_SITUACION' => 'MERCANCIA EN MURCIA',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '431',
				'NOM_SITUACION' => 'MERCANCIA EN PAMPLONA',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '432',
				'NOM_SITUACION' => 'MERCANCIA EN ORENSE',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '433',
				'NOM_SITUACION' => 'MERCANCIA EN OVIEDO',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '434',
				'NOM_SITUACION' => 'MERCANCIA EN PALENCIA',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '435',
				'NOM_SITUACION' => 'MERCANCIA EN LAS PALMAS G.C.',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '436',
				'NOM_SITUACION' => 'MERCANCIA EN PLAT. CALDAS',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '437',
				'NOM_SITUACION' => 'MERCANCIA EN SALAMANCA',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '438',
				'NOM_SITUACION' => 'MERCANCIA EN TENERIFE',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '439',
				'NOM_SITUACION' => 'MERCANCIA EN SANTANDER',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '440',
				'NOM_SITUACION' => 'MERCANCIA EN SEGOVIA',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '441',
				'NOM_SITUACION' => 'MERCANCIA EN SEVILLA',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '442',
				'NOM_SITUACION' => 'MERCANCIA EN SORIA',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '443',
				'NOM_SITUACION' => 'MERCANCIA EN TARRAGONA',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '444',
				'NOM_SITUACION' => 'MERCANCIA EN TERUEL',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '445',
				'NOM_SITUACION' => 'MERCANCIA EN TOLEDO',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '446',
				'NOM_SITUACION' => 'MERCANCIA EN VALENCIA',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '447',
				'NOM_SITUACION' => 'MERCANCIA EN VALLADOLID',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '448',
				'NOM_SITUACION' => 'MERCANCIA EN BILBAO',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '449',
				'NOM_SITUACION' => 'MERCANCIA EN ZAMORA',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '450',
				'NOM_SITUACION' => 'MERCANCIA EN ZARAGOZA',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '451',
				'NOM_SITUACION' => 'MERCANCIA EN ALGECIRAS',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '452',
				'NOM_SITUACION' => 'MERCANCIA EN LANZAROTE',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '453',
				'NOM_SITUACION' => 'MERCANCIA EN VALLES OCCIDENTAL',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '454',
				'NOM_SITUACION' => 'MERCANCIA EN GRANOLLERS',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '455',
				'NOM_SITUACION' => 'MERCANCIA EN CARTEGENA',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '456',
				'NOM_SITUACION' => 'MERCANCIA EN MELILLA',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '457',
				'NOM_SITUACION' => 'MERCANCIA EN EIBAR',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '458',
				'NOM_SITUACION' => 'MERCANCIA EN EL FERROL',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '459',
				'NOM_SITUACION' => 'MERCANCIA EN PLASENCIA',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '460',
				'NOM_SITUACION' => 'MERCANCIA EN FUERTEVENTURA',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '461',
				'NOM_SITUACION' => 'MERCANCIA EN PLAT. SEU URGELL',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '462',
				'NOM_SITUACION' => 'MERCANCIA EN IBIZA',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '463',
				'NOM_SITUACION' => 'MERCANCIA EN PLAT. TALAVERA',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '464',
				'NOM_SITUACION' => 'MERCANCIA EN MERIDA',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '465',
				'NOM_SITUACION' => 'MERCANCIA EN PLAT. ARANDA',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '466',
				'NOM_SITUACION' => 'MERCANCIA EN PLAT. CLI GETAFE',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '467',
				'NOM_SITUACION' => 'MERCANCIA EN PLAT. MIRANDA',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '468',
				'NOM_SITUACION' => 'MERCANCIA EN PONFERRADA',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '469',
				'NOM_SITUACION' => 'MERCANCIA EN PLAT. PONF-VALDEO',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '470',
				'NOM_SITUACION' => 'MERCANCIA EN STA.CRUZ PALMA',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '471',
				'NOM_SITUACION' => 'MERCANCIA EN SANTIAGO',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '472',
				'NOM_SITUACION' => 'MERCANCIA EN VIGO',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '473',
				'NOM_SITUACION' => 'MERCANCIA EN MENORCA',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '474',
				'NOM_SITUACION' => 'MERCANCIA EN CEUTA',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '475',
				'NOM_SITUACION' => 'MERCANCIA EN DON BENITO',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '476',
				'NOM_SITUACION' => 'MERCANCIA EN PLAT. SANTAREN',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '477',
				'NOM_SITUACION' => 'MERCANCIA EN ANDORRA',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '478',
				'NOM_SITUACION' => 'MERCANCIA EN LORCA',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '479',
				'NOM_SITUACION' => 'MERCANCIA EN PLAT. LUCENA',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '480',
				'NOM_SITUACION' => 'MERCANCIA EN INTNAL. MADRID',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '481',
				'NOM_SITUACION' => 'MERCANCIA EN PLAT. LEIRIA',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '482',
				'NOM_SITUACION' => 'MERCANCIA EN GUARDA',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '483',
				'NOM_SITUACION' => 'MERCANCIA EN LISBOA',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '484',
				'NOM_SITUACION' => 'MERCANCIA EN PORTO',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '485',
				'NOM_SITUACION' => 'MERCANCIA EN EVORA',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '486',
				'NOM_SITUACION' => 'MERCANCIA EN FARO',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '487',
				'NOM_SITUACION' => 'MERCANCIA EN AVEIRO',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '488',
				'NOM_SITUACION' => 'MERCANCIA EN PLAT. COSLADA',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '489',
				'NOM_SITUACION' => 'MERCANCIA EN INTNAL. BCN',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '490',
				'NOM_SITUACION' => 'MERCANCIA EN BADALONA',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '491',
				'NOM_SITUACION' => 'MERCANCIA EN BAIX LLOBREGAT',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '492',
				'NOM_SITUACION' => 'MERCANCIA EN HOSPITALET ZF',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '493',
				'NOM_SITUACION' => 'MERCANCIA EN B-TARRAGONA',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '494',
				'NOM_SITUACION' => 'MERCANCIA EN ALMACENAJE-BCN',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '495',
				'NOM_SITUACION' => 'MERCANCIA EN MANRESA-IGUALAD',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '496',
				'NOM_SITUACION' => 'MERCANCIA EN PLAT. VLC. SUR',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '497',
				'NOM_SITUACION' => 'MERCANCIA EN SEUR ESPANA',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '498',
				'NOM_SITUACION' => 'MERCANCIA EN PLAT. ECIJA',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '499',
				'NOM_SITUACION' => 'MERCANCIA EN PLAT. CONDADO',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '510',
				'NOM_SITUACION' => 'FALTAN BULTOS',
				'Grupo'         => 'INCIDENCIA',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '511',
				'NOM_SITUACION' => 'FALTA EXPEDICION COMPLETA',
				'Grupo'         => 'INCIDENCIA',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '512',
				'NOM_SITUACION' => 'FALTA POR SERVICIO (48 HORAS)',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '513',
				'NOM_SITUACION' => 'FALTA DOCUMENTACION',
				'Grupo'         => 'APORTAR SOLUCION',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '515',
				'NOM_SITUACION' => 'PENDIENTE DE REPARTO EN PLAZA',
				'Grupo'         => 'INCIDENCIA',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '516',
				'NOM_SITUACION' => 'EXPEDICION PARCIAL EN REPARTO',
				'Grupo'         => 'INCIDENCIA',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '518',
				'NOM_SITUACION' => 'EXP. SIN CONTROLAR POR FIESTA',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '519',
				'NOM_SITUACION' => 'EXPEDICION PARCIAL ENTREGADA',
				'Grupo'         => 'INCIDENCIA',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '520',
				'NOM_SITUACION' => 'DESTINATARIO DESCONOCIDO',
				'Grupo'         => 'APORTAR SOLUCION',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '521',
				'NOM_SITUACION' => 'DOMICILIO DESCONOCIDO',
				'Grupo'         => 'APORTAR SOLUCION',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '522',
				'NOM_SITUACION' => 'AUSENCIA PROLONGADA',
				'Grupo'         => 'APORTAR SOLUCION',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '523',
				'NOM_SITUACION' => 'CERRADO O PRIMERA AUSENCIA',
				'Grupo'         => 'APORTAR SOLUCION',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '524',
				'NOM_SITUACION' => 'CAMBIO DE DOMICILIO',
				'Grupo'         => 'APORTAR SOLUCION',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '525',
				'NOM_SITUACION' => 'FIESTA LOCAL',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '526',
				'NOM_SITUACION' => 'ACCESO IMPOSIBLE AL CLIENTE',
				'Grupo'         => 'APORTAR SOLUCION',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '527',
				'NOM_SITUACION' => 'NO CONTESTA TELEFONO',
				'Grupo'         => 'APORTAR SOLUCION',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '528',
				'NOM_SITUACION' => 'VACACIONES DEL CLIENTE',
				'Grupo'         => 'APORTAR SOLUCION',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '529',
				'NOM_SITUACION' => 'CERRADO DEFINITIVAMENTE',
				'Grupo'         => 'APORTAR SOLUCION',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '530',
				'NOM_SITUACION' => 'PENDIENTE EN RECOGERAN',
				'Grupo'         => 'DISPONIBLE PARA RECOGER EN TIENDA',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '531',
				'NOM_SITUACION' => 'RETENER EN PLAZA',
				'Grupo'         => 'APORTAR SOLUCION',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '532',
				'NOM_SITUACION' => 'NO HAY PERSONA DE CONTACTO',
				'Grupo'         => 'APORTAR SOLUCION',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '533',
				'NOM_SITUACION' => 'SATURACION O FALTA DE TIEMPO',
				'Grupo'         => 'INCIDENCIA',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '534',
				'NOM_SITUACION' => 'COMPROBAR SI ES REEMBOLSO',
				'Grupo'         => 'APORTAR SOLUCION',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '535',
				'NOM_SITUACION' => 'EXPEDICION EXTRAVIADA',
				'Grupo'         => 'INCIDENCIA',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '537',
				'NOM_SITUACION' => 'EXPEDICION DETERIORADA',
				'Grupo'         => 'INCIDENCIA',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '538',
				'NOM_SITUACION' => 'EXP. DETERIORADA EN REPARTO',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '540',
				'NOM_SITUACION' => 'AVISARAN',
				'Grupo'         => 'APORTAR SOLUCION',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '541',
				'NOM_SITUACION' => 'SIN EFECTIVO A LA ENTREGA',
				'Grupo'         => 'APORTAR SOLUCION',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '542',
				'NOM_SITUACION' => 'INDICAN DEVOLUCION',
				'Grupo'         => 'DEVOLUCION EN CURSO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '543',
				'NOM_SITUACION' => 'PDTE REPARTO DEVOLUCION MASIVA',
				'Grupo'         => 'DEVOLUCION EN CURSO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '544',
				'NOM_SITUACION' => 'CLIMA ADVERSO',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '545',
				'NOM_SITUACION' => 'NO CONOCEN AL REMITENTE',
				'Grupo'         => 'APORTAR SOLUCION',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '546',
				'NOM_SITUACION' => 'QUIEREN ABRIR EL PAQUETE',
				'Grupo'         => 'APORTAR SOLUCION',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '547',
				'NOM_SITUACION' => 'CONCERTADO PROXIMO REPARTO',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '548',
				'NOM_SITUACION' => 'CONCERTADA ENTREGA CON RMTE.',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '549',
				'NOM_SITUACION' => 'PENDIENTE ENTREGA CC/GS',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '550',
				'NOM_SITUACION' => 'NO ACEPTAN POR ROTURA',
				'Grupo'         => 'APORTAR SOLUCION',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '551',
				'NOM_SITUACION' => 'NO ACEPTAN PORTES',
				'Grupo'         => 'APORTAR SOLUCION',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '552',
				'NOM_SITUACION' => 'NO ACEPTAN REEMBOLSO',
				'Grupo'         => 'APORTAR SOLUCION',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '553',
				'NOM_SITUACION' => 'NO ACEPTAN DESPACHO O IMPUESTO',
				'Grupo'         => 'APORTAR SOLUCION',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '554',
				'NOM_SITUACION' => 'NO QUIERE FIRMAR ALBARAN/CDE',
				'Grupo'         => 'APORTAR SOLUCION',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '555',
				'NOM_SITUACION' => 'NO ACEPTAN GASTOS REEMBOLSO',
				'Grupo'         => 'APORTAR SOLUCION',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '556',
				'NOM_SITUACION' => 'QUIEREN PAGAR TALON SIN CONFOR',
				'Grupo'         => 'APORTAR SOLUCION',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '557',
				'NOM_SITUACION' => 'SEGUNDA OLEADA',
				'Grupo'         => 'INCIDENCIA',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '558',
				'NOM_SITUACION' => 'FALTA DE TIEMPO NAVE',
				'Grupo'         => 'INCIDENCIA',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '559',
				'NOM_SITUACION' => 'PENDIENTE CONCERTACION CC/GS',
				'Grupo'         => 'INCIDENCIA',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '560',
				'NOM_SITUACION' => 'NO TIENE PREPARADO EL CAMBIO',
				'Grupo'         => 'APORTAR SOLUCION',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '563',
				'NOM_SITUACION' => 'NO SALIO A REPARTO. CERRADO',
				'Grupo'         => 'INCIDENCIA',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '564',
				'NOM_SITUACION' => 'ENTREGA CON MEDIOS ADICIONALES',
				'Grupo'         => 'INCIDENCIA',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '567',
				'NOM_SITUACION' => 'PDTE. CONCERTACION AUTOMATICA',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '569',
				'NOM_SITUACION' => 'PENDIENTE EN PUNTO',
				'Grupo'         => 'DISPONIBLE PARA RECOGER EN TIENDA',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '571',
				'NOM_SITUACION' => 'DEVOLVER.DEST.RECHAZA PUDO',
				'Grupo'         => 'DEVOLUCION EN CURSO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '572',
				'NOM_SITUACION' => 'DEVOLVER.PLZO.CUMPLIDO PUDO',
				'Grupo'         => 'DEVOLUCION EN CURSO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '574',
				'NOM_SITUACION' => 'RECEPCIONADO EN PUNTO',
				'Grupo'         => 'DISPONIBLE PARA RECOGER EN TIENDA',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '717',
				'NOM_SITUACION' => 'FALTA FACTURA',
				'Grupo'         => 'APORTAR SOLUCION',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '718',
				'NOM_SITUACION' => 'FALTA DESCRIPCION DE MERCANCIA',
				'Grupo'         => 'APORTAR SOLUCION',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '719',
				'NOM_SITUACION' => 'FALTA VALOR DE LA MERCANCIA',
				'Grupo'         => 'APORTAR SOLUCION',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '721',
				'NOM_SITUACION' => 'FALTA NIF/CIF DEL REMITENTE',
				'Grupo'         => 'APORTAR SOLUCION',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '722',
				'NOM_SITUACION' => 'FALTA NIF/CIF DEL DESTINATARIO',
				'Grupo'         => 'APORTAR SOLUCION',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '725',
				'NOM_SITUACION' => 'FALTA BULTO Y FACTURA',
				'Grupo'         => 'APORTAR SOLUCION',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '731',
				'NOM_SITUACION' => 'FALTA TITULAR CIF/NIF REMITENT',
				'Grupo'         => 'APORTAR SOLUCION',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '732',
				'NOM_SITUACION' => 'FALTA TITULAR CIF/NIF DESTINAT',
				'Grupo'         => 'APORTAR SOLUCION',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '799',
				'NOM_SITUACION' => 'MERCANCIA PDTE DE EMBARCAR',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '849',
				'NOM_SITUACION' => 'INSPECCION NO ADUANERA',
				'Grupo'         => 'INCIDENCIA',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '853',
				'NOM_SITUACION' => 'EMBALAJE INSUFICIENTE',
				'Grupo'         => 'APORTAR SOLUCION',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '862',
				'NOM_SITUACION' => 'DECLARACION ERRONEA',
				'Grupo'         => 'APORTAR SOLUCION',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '864',
				'NOM_SITUACION' => 'ESPERANDO PAGO DE IMPUESTOS',
				'Grupo'         => 'APORTAR SOLUCION',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '865',
				'NOM_SITUACION' => 'ADUANAS:DATOS INSUF./INCORRECT',
				'Grupo'         => 'APORTAR SOLUCION',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '866',
				'NOM_SITUACION' => 'MATERIAL RESTRINGIDO',
				'Grupo'         => 'APORTAR SOLUCION',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '868',
				'NOM_SITUACION' => 'PO BOX SIN TELEFONO',
				'Grupo'         => 'APORTAR SOLUCION',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '869',
				'NOM_SITUACION' => 'ESPERANDO INSTRUCCION REMITENT',
				'Grupo'         => 'APORTAR SOLUCION',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '876',
				'NOM_SITUACION' => 'PERDIDA CONEXION ARRASTRE INTL',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '879',
				'NOM_SITUACION' => 'MAL TIEMPO',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '880',
				'NOM_SITUACION' => 'HUELGA',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '881',
				'NOM_SITUACION' => 'ENVIO ROBADO',
				'Grupo'         => 'INCIDENCIA',
			),
			array(
				'COD_TIPO_SITU' => 'I',
				'COD_SITU'      => '882',
				'NOM_SITUACION' => 'BULTO DANADO',
				'Grupo'         => 'INCIDENCIA',
			),
			array(
				'COD_TIPO_SITU' => 'J',
				'COD_SITU'      => '100',
				'NOM_SITUACION' => 'CONCERTADO PROXIMO REPARTO',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'J',
				'COD_SITU'      => '833',
				'NOM_SITUACION' => 'INTERNACIONAL DEVOLVER A ORIGE',
				'Grupo'         => 'DEVOLUCION EN CURSO',
			),
			array(
				'COD_TIPO_SITU' => 'K',
				'COD_SITU'      => '521',
				'NOM_SITUACION' => 'ANUL. FALTA Y ACUERDO FRANQ.',
				'Grupo'         => 'INCIDENCIA',
			),
			array(
				'COD_TIPO_SITU' => 'K',
				'COD_SITU'      => '560',
				'NOM_SITUACION' => 'Siniestro',
				'Grupo'         => 'INCIDENCIA',
			),
			array(
				'COD_TIPO_SITU' => 'L',
				'COD_SITU'      => '1',
				'NOM_SITUACION' => 'Entregado',
				'Grupo'         => 'ENTREGADO',
			),
			array(
				'COD_TIPO_SITU' => 'L',
				'COD_SITU'      => '3',
				'NOM_SITUACION' => 'ENTREGADO POR BULTO',
				'Grupo'         => 'ENTREGADO',
			),
			array(
				'COD_TIPO_SITU' => 'L',
				'COD_SITU'      => '7',
				'NOM_SITUACION' => 'Liquidada entrega parcial',
				'Grupo'         => 'INCIDENCIA',
			),
			array(
				'COD_TIPO_SITU' => 'L',
				'COD_SITU'      => '10',
				'NOM_SITUACION' => 'ENTREGADO EN PUNTO',
				'Grupo'         => 'ENTREGADO',
			),
			array(
				'COD_TIPO_SITU' => 'L',
				'COD_SITU'      => '20',
				'NOM_SITUACION' => 'ENTREGADO AL VECINO',
				'Grupo'         => 'ENTREGADO',
			),
			array(
				'COD_TIPO_SITU' => 'L',
				'COD_SITU'      => '60',
				'NOM_SITUACION' => 'ENTREGADO CAMBIO SIN RETORNO',
				'Grupo'         => 'ENTREGADO',
			),
			array(
				'COD_TIPO_SITU' => 'L',
				'COD_SITU'      => '91',
				'NOM_SITUACION' => 'LIQUIDADO EXPEDIC. EXTRAVIADA',
				'Grupo'         => 'INCIDENCIA',
			),
			array(
				'COD_TIPO_SITU' => 'L',
				'COD_SITU'      => '300',
				'NOM_SITUACION' => 'Liquidado DEVUELTO',
				'Grupo'         => 'DEVOLUCION EN CURSO',
			),
			array(
				'COD_TIPO_SITU' => 'L',
				'COD_SITU'      => '301',
				'NOM_SITUACION' => 'LIQUIDADO REENVIO A OTRA PLAZA',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'L',
				'COD_SITU'      => '833',
				'NOM_SITUACION' => 'DEVOLVER A ORIGEN',
				'Grupo'         => 'DEVOLUCION EN CURSO',
			),
			array(
				'COD_TIPO_SITU' => 'L',
				'COD_SITU'      => '872',
				'NOM_SITUACION' => 'ENTREGADO A VECINO',
				'Grupo'         => 'ENTREGADO',
			),
			array(
				'COD_TIPO_SITU' => 'L',
				'COD_SITU'      => '873',
				'NOM_SITUACION' => 'ENTREGADO A BROKER',
				'Grupo'         => 'ENTREGADO',
			),
			array(
				'COD_TIPO_SITU' => 'M',
				'COD_SITU'      => '1',
				'NOM_SITUACION' => 'Error tipo pago cobrado',
				'Grupo'         => 'ENTREGADO',
			),
			array(
				'COD_TIPO_SITU' => 'M',
				'COD_SITU'      => '2',
				'NOM_SITUACION' => 'Error tipo pago factura',
				'Grupo'         => 'ENTREGADO',
			),
			array(
				'COD_TIPO_SITU' => 'M',
				'COD_SITU'      => '3',
				'NOM_SITUACION' => 'Error tipo pago recibo',
				'Grupo'         => 'ENTREGADO',
			),
			array(
				'COD_TIPO_SITU' => 'M',
				'COD_SITU'      => '4',
				'NOM_SITUACION' => 'Error tipo pago sin cargo',
				'Grupo'         => 'ENTREGADO',
			),
			array(
				'COD_TIPO_SITU' => 'M',
				'COD_SITU'      => '5',
				'NOM_SITUACION' => 'Error tipo pagado',
				'Grupo'         => 'ENTREGADO',
			),
			array(
				'COD_TIPO_SITU' => 'M',
				'COD_SITU'      => '6',
				'NOM_SITUACION' => 'Error tipo pago talon',
				'Grupo'         => 'ENTREGADO',
			),
			array(
				'COD_TIPO_SITU' => 'M',
				'COD_SITU'      => '9',
				'NOM_SITUACION' => 'Error sin tipo pago',
				'Grupo'         => 'ENTREGADO',
			),
			array(
				'COD_TIPO_SITU' => 'M',
				'COD_SITU'      => '10',
				'NOM_SITUACION' => 'Cobrada con talon',
				'Grupo'         => 'ENTREGADO',
			),
			array(
				'COD_TIPO_SITU' => 'M',
				'COD_SITU'      => '11',
				'NOM_SITUACION' => 'Error total cobrado distinto',
				'Grupo'         => 'ENTREGADO',
			),
			array(
				'COD_TIPO_SITU' => 'M',
				'COD_SITU'      => '12',
				'NOM_SITUACION' => 'Error no tiene codigo contable',
				'Grupo'         => 'ENTREGADO',
			),
			array(
				'COD_TIPO_SITU' => 'M',
				'COD_SITU'      => '13',
				'NOM_SITUACION' => 'Error no tiene telefono',
				'Grupo'         => 'ENTREGADO',
			),
			array(
				'COD_TIPO_SITU' => 'M',
				'COD_SITU'      => '14',
				'NOM_SITUACION' => 'Cliente distinto al de cartera',
				'Grupo'         => 'ENTREGADO',
			),
			array(
				'COD_TIPO_SITU' => 'M',
				'COD_SITU'      => '15',
				'NOM_SITUACION' => 'Cliente estricto contado',
				'Grupo'         => 'ENTREGADO',
			),
			array(
				'COD_TIPO_SITU' => 'M',
				'COD_SITU'      => '16',
				'NOM_SITUACION' => 'No existe el codigo contable',
				'Grupo'         => 'ENTREGADO',
			),
			array(
				'COD_TIPO_SITU' => 'M',
				'COD_SITU'      => '17',
				'NOM_SITUACION' => 'Mas de un cliente con = Tlfno.',
				'Grupo'         => 'ENTREGADO',
			),
			array(
				'COD_TIPO_SITU' => 'M',
				'COD_SITU'      => '18',
				'NOM_SITUACION' => 'No existe el telefono',
				'Grupo'         => 'ENTREGADO',
			),
			array(
				'COD_TIPO_SITU' => 'M',
				'COD_SITU'      => '19',
				'NOM_SITUACION' => 'Repartidor distinto en cartera',
				'Grupo'         => 'ENTREGADO',
			),
			array(
				'COD_TIPO_SITU' => 'M',
				'COD_SITU'      => '20',
				'NOM_SITUACION' => 'Cliente contable sin chequear',
				'Grupo'         => 'ENTREGADO',
			),
			array(
				'COD_TIPO_SITU' => 'M',
				'COD_SITU'      => '21',
				'NOM_SITUACION' => 'Falta Nombre Firma Receptor',
				'Grupo'         => 'ENTREGADO',
			),
			array(
				'COD_TIPO_SITU' => 'M',
				'COD_SITU'      => '22',
				'NOM_SITUACION' => 'POSIBLE LIQUIDACION PARCIAL',
				'Grupo'         => 'INCIDENCIA',
			),
			array(
				'COD_TIPO_SITU' => 'M',
				'COD_SITU'      => '26',
				'NOM_SITUACION' => 'CDE PENDIENTE DIGITALIZAR',
				'Grupo'         => 'ENTREGADO',
			),
			array(
				'COD_TIPO_SITU' => 'M',
				'COD_SITU'      => '27',
				'NOM_SITUACION' => 'CDE PENDIENTE RECIBIR IMAGEN',
				'Grupo'         => 'ENTREGADO',
			),
			array(
				'COD_TIPO_SITU' => 'M',
				'COD_SITU'      => '60',
				'NOM_SITUACION' => 'ENTREGA SIN CONTRASTAR RETORNO',
				'Grupo'         => 'ENTREGADO',
			),
			array(
				'COD_TIPO_SITU' => 'M',
				'COD_SITU'      => '999',
				'NOM_SITUACION' => 'ENTREGA  RELACION A VERIFICAR',
				'Grupo'         => 'ENTREGADO',
			),
			array(
				'COD_TIPO_SITU' => 'O',
				'COD_SITU'      => '1',
				'NOM_SITUACION' => 'Fecha prevista otro dia',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'O',
				'COD_SITU'      => '2',
				'NOM_SITUACION' => 'FIESTA LOCAL',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'R',
				'COD_SITU'      => '802',
				'NOM_SITUACION' => 'PERD. CONEXION CAUSA AJENA',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'S',
				'COD_SITU'      => '4',
				'NOM_SITUACION' => 'Asignada por almacen',
				'Grupo'         => 'EN TRANSITO',
			),
			array(
				'COD_TIPO_SITU' => 'T',
				'COD_SITU'      => '859',
				'NOM_SITUACION' => 'TRANSITO INTERNACIONAL',
				'Grupo'         => 'EN TRANSITO',
			),
		);