<?php if ( ! defined( 'ABSPATH' ) ) exit; // Exit if accessed directly

return array(
	'BG-01' => __( 'Blagoevgrad', SEUR_TEXTDOMAIN ),
	'BG-02' => __( 'Burgas', SEUR_TEXTDOMAIN ),
	'BG-08' => __( 'Dobrich', SEUR_TEXTDOMAIN ),
	'BG-07' => __( 'Gabrovo', SEUR_TEXTDOMAIN ),
	'BG-26' => __( 'Haskovo', SEUR_TEXTDOMAIN ),
	'BG-09' => __( 'Kardzhali', SEUR_TEXTDOMAIN ),
	'BG-10' => __( 'Kyustendil', SEUR_TEXTDOMAIN ),
	'BG-11' => __( 'Lovech', SEUR_TEXTDOMAIN ),
	'BG-12' => __( 'Montana', SEUR_TEXTDOMAIN ),
	'BG-13' => __( 'Pazardzhik', SEUR_TEXTDOMAIN ),
	'BG-14' => __( 'Pernik', SEUR_TEXTDOMAIN ),
	'BG-15' => __( 'Pleven', SEUR_TEXTDOMAIN ),
	'BG-16' => __( 'Plovdiv', SEUR_TEXTDOMAIN ),
	'BG-17' => __( 'Razgrad', SEUR_TEXTDOMAIN ),
	'BG-18' => __( 'Ruse', SEUR_TEXTDOMAIN ),
	'BG-27' => __( 'Shumen', SEUR_TEXTDOMAIN ),
	'BG-19' => __( 'Silistra', SEUR_TEXTDOMAIN ),
	'BG-20' => __( 'Sliven', SEUR_TEXTDOMAIN ),
	'BG-21' => __( 'Smolyan', SEUR_TEXTDOMAIN ),
	'BG-23' => __( 'Sofia', SEUR_TEXTDOMAIN ),
	'BG-22' => __( 'Sofia-Grad', SEUR_TEXTDOMAIN ),
	'BG-24' => __( 'Stara Zagora', SEUR_TEXTDOMAIN ),
	'BG-25' => __( 'Targovishte', SEUR_TEXTDOMAIN ),
	'BG-03' => __( 'Varna', SEUR_TEXTDOMAIN ),
	'BG-04' => __( 'Veliko Tarnovo', SEUR_TEXTDOMAIN ),
	'BG-05' => __( 'Vidin', SEUR_TEXTDOMAIN ),
	'BG-06' => __( 'Vratsa', SEUR_TEXTDOMAIN ),
	'BG-28' => __( 'Yambol', SEUR_TEXTDOMAIN ),
);
