<?php if ( ! defined( 'ABSPATH' ) ) exit; // Exit if accessed directly

return array(
	'BG-01' => __( 'Blagoevgrad', 'seur-oficial' ),
	'BG-02' => __( 'Burgas', 'seur-oficial' ),
	'BG-08' => __( 'Dobrich', 'seur-oficial' ),
	'BG-07' => __( 'Gabrovo', 'seur-oficial' ),
	'BG-26' => __( 'Haskovo', 'seur-oficial' ),
	'BG-09' => __( 'Kardzhali', 'seur-oficial' ),
	'BG-10' => __( 'Kyustendil', 'seur-oficial' ),
	'BG-11' => __( 'Lovech', 'seur-oficial' ),
	'BG-12' => __( 'Montana', 'seur-oficial' ),
	'BG-13' => __( 'Pazardzhik', 'seur-oficial' ),
	'BG-14' => __( 'Pernik', 'seur-oficial' ),
	'BG-15' => __( 'Pleven', 'seur-oficial' ),
	'BG-16' => __( 'Plovdiv', 'seur-oficial' ),
	'BG-17' => __( 'Razgrad', 'seur-oficial' ),
	'BG-18' => __( 'Ruse', 'seur-oficial' ),
	'BG-27' => __( 'Shumen', 'seur-oficial' ),
	'BG-19' => __( 'Silistra', 'seur-oficial' ),
	'BG-20' => __( 'Sliven', 'seur-oficial' ),
	'BG-21' => __( 'Smolyan', 'seur-oficial' ),
	'BG-23' => __( 'Sofia', 'seur-oficial' ),
	'BG-22' => __( 'Sofia-Grad', 'seur-oficial' ),
	'BG-24' => __( 'Stara Zagora', 'seur-oficial' ),
	'BG-25' => __( 'Targovishte', 'seur-oficial' ),
	'BG-03' => __( 'Varna', 'seur-oficial' ),
	'BG-04' => __( 'Veliko Tarnovo', 'seur-oficial' ),
	'BG-05' => __( 'Vidin', 'seur-oficial' ),
	'BG-06' => __( 'Vratsa', 'seur-oficial' ),
	'BG-28' => __( 'Yambol', 'seur-oficial' ),
);
