<?php if ( ! defined( 'ABSPATH' ) ) exit; // Exit if accessed directly

return array(
	'AC' => __( 'Acre', 'seur-oficial' ),
	'AL' => __( 'Alagoas', 'seur-oficial' ),
	'AP' => __( 'Amap&aacute;', 'seur-oficial' ),
	'AM' => __( 'Amazonas', 'seur-oficial' ),
	'BA' => __( 'Bahia', 'seur-oficial' ),
	'CE' => __( 'Cear&aacute;', 'seur-oficial' ),
	'DF' => __( 'Distrito Federal', 'seur-oficial' ),
	'ES' => __( 'Esp&iacute;rito Santo', 'seur-oficial' ),
	'GO' => __( 'Goi&aacute;s', 'seur-oficial' ),
	'MA' => __( 'Maranh&atilde;o', 'seur-oficial' ),
	'MT' => __( 'Mato Grosso', 'seur-oficial' ),
	'MS' => __( 'Mato Grosso do Sul', 'seur-oficial' ),
	'MG' => __( 'Minas Gerais', 'seur-oficial' ),
	'PA' => __( 'Par&aacute;', 'seur-oficial' ),
	'PB' => __( 'Para&iacute;ba', 'seur-oficial' ),
	'PR' => __( 'Paran&aacute;', 'seur-oficial' ),
	'PE' => __( 'Pernambuco', 'seur-oficial' ),
	'PI' => __( 'Piau&iacute;', 'seur-oficial' ),
	'RJ' => __( 'Rio de Janeiro', 'seur-oficial' ),
	'RN' => __( 'Rio Grande do Norte', 'seur-oficial' ),
	'RS' => __( 'Rio Grande do Sul', 'seur-oficial' ),
	'RO' => __( 'Rond&ocirc;nia', 'seur-oficial' ),
	'RR' => __( 'Roraima', 'seur-oficial' ),
	'SC' => __( 'Santa Catarina', 'seur-oficial' ),
	'SP' => __( 'S&atilde;o Paulo', 'seur-oficial' ),
	'SE' => __( 'Sergipe', 'seur-oficial' ),
	'TO' => __( 'Tocantins', 'seur-oficial' )
);
