<?php if ( ! defined( 'ABSPATH' ) ) exit; // Exit if accessed directly

return array(
	'AC' => __( 'Daerah Istimewa Aceh', 'seur' ),
	'SU' => __( 'Sumatera Utara', 'seur' ),
	'SB' => __( 'Sumatera Barat', 'seur' ),
	'RI' => __( 'Riau', 'seur' ),
	'KR' => __( 'Kepulauan Riau', 'seur' ),
	'JA' => __( 'Jambi', 'seur' ),
	'SS' => __( 'Sumatera Selatan', 'seur' ),
	'BB' => __( 'Bangka Belitung', 'seur' ),
	'BE' => __( 'Bengkulu', 'seur' ),
	'LA' => __( 'Lampung', 'seur' ),
	'JK' => __( 'DKI Jakarta', 'seur' ),
	'JB' => __( 'Jawa Barat', 'seur' ),
	'BT' => __( 'Banten', 'seur' ),
	'JT' => __( 'Jawa Tengah', 'seur' ),
	'JI' => __( 'Jawa Timur', 'seur' ),
	'YO' => __( 'Daerah Istimewa Yogyakarta', 'seur' ),
	'BA' => __( 'Bali', 'seur' ),
	'NB' => __( 'Nusa Tenggara Barat', 'seur' ),
	'NT' => __( 'Nusa Tenggara Timur', 'seur' ),
	'KB' => __( 'Kalimantan Barat', 'seur' ),
	'KT' => __( 'Kalimantan Tengah', 'seur' ),
	'KI' => __( 'Kalimantan Timur', 'seur' ),
	'KS' => __( 'Kalimantan Selatan', 'seur' ),
	'KU' => __( 'Kalimantan Utara', 'seur' ),
	'SA' => __( 'Sulawesi Utara', 'seur' ),
	'ST' => __( 'Sulawesi Tengah', 'seur' ),
	'SG' => __( 'Sulawesi Tenggara', 'seur' ),
	'SR' => __( 'Sulawesi Barat', 'seur' ),
	'SN' => __( 'Sulawesi Selatan', 'seur' ),
	'GO' => __( 'Gorontalo', 'seur' ),
	'MA' => __( 'Maluku', 'seur' ),
	'MU' => __( 'Maluku Utara', 'seur' ),
	'PA' => __( 'Papua', 'seur' ),
	'PB' => __( 'Papua Barat', 'seur' )
);
