<?php if ( ! defined( 'ABSPATH' ) ) exit; // Exit if accessed directly

return array(
	'AC' => __( 'Daerah Istimewa Aceh', SEUR_TEXTDOMAIN ),
	'SU' => __( 'Sumatera Utara', SEUR_TEXTDOMAIN ),
	'SB' => __( 'Sumatera Barat', SEUR_TEXTDOMAIN ),
	'RI' => __( 'Riau', SEUR_TEXTDOMAIN ),
	'KR' => __( 'Kepulauan Riau', SEUR_TEXTDOMAIN ),
	'JA' => __( 'Jambi', SEUR_TEXTDOMAIN ),
	'SS' => __( 'Sumatera Selatan', SEUR_TEXTDOMAIN ),
	'BB' => __( 'Bangka Belitung', SEUR_TEXTDOMAIN ),
	'BE' => __( 'Bengkulu', SEUR_TEXTDOMAIN ),
	'LA' => __( 'Lampung', SEUR_TEXTDOMAIN ),
	'JK' => __( 'DKI Jakarta', SEUR_TEXTDOMAIN ),
	'JB' => __( 'Jawa Barat', SEUR_TEXTDOMAIN ),
	'BT' => __( 'Banten', SEUR_TEXTDOMAIN ),
	'JT' => __( 'Jawa Tengah', SEUR_TEXTDOMAIN ),
	'JI' => __( 'Jawa Timur', SEUR_TEXTDOMAIN ),
	'YO' => __( 'Daerah Istimewa Yogyakarta', SEUR_TEXTDOMAIN ),
	'BA' => __( 'Bali', SEUR_TEXTDOMAIN ),
	'NB' => __( 'Nusa Tenggara Barat', SEUR_TEXTDOMAIN ),
	'NT' => __( 'Nusa Tenggara Timur', SEUR_TEXTDOMAIN ),
	'KB' => __( 'Kalimantan Barat', SEUR_TEXTDOMAIN ),
	'KT' => __( 'Kalimantan Tengah', SEUR_TEXTDOMAIN ),
	'KI' => __( 'Kalimantan Timur', SEUR_TEXTDOMAIN ),
	'KS' => __( 'Kalimantan Selatan', SEUR_TEXTDOMAIN ),
	'KU' => __( 'Kalimantan Utara', SEUR_TEXTDOMAIN ),
	'SA' => __( 'Sulawesi Utara', SEUR_TEXTDOMAIN ),
	'ST' => __( 'Sulawesi Tengah', SEUR_TEXTDOMAIN ),
	'SG' => __( 'Sulawesi Tenggara', SEUR_TEXTDOMAIN ),
	'SR' => __( 'Sulawesi Barat', SEUR_TEXTDOMAIN ),
	'SN' => __( 'Sulawesi Selatan', SEUR_TEXTDOMAIN ),
	'GO' => __( 'Gorontalo', SEUR_TEXTDOMAIN ),
	'MA' => __( 'Maluku', SEUR_TEXTDOMAIN ),
	'MU' => __( 'Maluku Utara', SEUR_TEXTDOMAIN ),
	'PA' => __( 'Papua', SEUR_TEXTDOMAIN ),
	'PB' => __( 'Papua Barat', SEUR_TEXTDOMAIN )
);
