<?php if ( ! defined( 'ABSPATH' ) ) exit; // Exit if accessed directly

return array(
	'AP' => __( 'Andhra Pradesh', SEUR_TEXTDOMAIN ),
	'AR' => __( 'Arunachal Pradesh', SEUR_TEXTDOMAIN ),
	'AS' => __( 'Assam', SEUR_TEXTDOMAIN ),
	'BR' => __( 'Bihar', SEUR_TEXTDOMAIN ),
	'CT' => __( 'Chhattisgarh', SEUR_TEXTDOMAIN ),
	'GA' => __( 'Goa', SEUR_TEXTDOMAIN ),
	'GJ' => __( 'Gujarat', SEUR_TEXTDOMAIN ),
	'HR' => __( 'Haryana', SEUR_TEXTDOMAIN ),
	'HP' => __( 'Himachal Pradesh', SEUR_TEXTDOMAIN ),
	'JK' => __( 'Jammu and Kashmir', SEUR_TEXTDOMAIN ),
	'JH' => __( 'Jharkhand', SEUR_TEXTDOMAIN ),
	'KA' => __( 'Karnataka', SEUR_TEXTDOMAIN ),
	'KL' => __( 'Kerala', SEUR_TEXTDOMAIN ),
	'MP' => __( 'Madhya Pradesh', SEUR_TEXTDOMAIN ),
	'MH' => __( 'Maharashtra', SEUR_TEXTDOMAIN ),
	'MN' => __( 'Manipur', SEUR_TEXTDOMAIN ),
	'ML' => __( 'Meghalaya', SEUR_TEXTDOMAIN ),
	'MZ' => __( 'Mizoram', SEUR_TEXTDOMAIN ),
	'NL' => __( 'Nagaland', SEUR_TEXTDOMAIN ),
	'OR' => __( 'Orissa', SEUR_TEXTDOMAIN ),
	'PB' => __( 'Punjab', SEUR_TEXTDOMAIN ),
	'RJ' => __( 'Rajasthan', SEUR_TEXTDOMAIN ),
	'SK' => __( 'Sikkim', SEUR_TEXTDOMAIN ),
	'TN' => __( 'Tamil Nadu', SEUR_TEXTDOMAIN ),
	'TS' => __( 'Telangana', SEUR_TEXTDOMAIN ),
	'TR' => __( 'Tripura', SEUR_TEXTDOMAIN ),
	'UK' => __( 'Uttarakhand', SEUR_TEXTDOMAIN ),
	'UP' => __( 'Uttar Pradesh', SEUR_TEXTDOMAIN ),
	'WB' => __( 'West Bengal', SEUR_TEXTDOMAIN ),
	'AN' => __( 'Andaman and Nicobar Islands', SEUR_TEXTDOMAIN ),
	'CH' => __( 'Chandigarh', SEUR_TEXTDOMAIN ),
	'DN' => __( 'Dadar and Nagar Haveli', SEUR_TEXTDOMAIN ),
	'DD' => __( 'Daman and Diu', SEUR_TEXTDOMAIN ),
	'DL' => __( 'Delhi', SEUR_TEXTDOMAIN ),
	'LD' => __( 'Lakshadeep', SEUR_TEXTDOMAIN ),
	'PY' => __( 'Pondicherry (Puducherry)', SEUR_TEXTDOMAIN )
);
