<?php if ( ! defined( 'ABSPATH' ) ) exit; // Exit if accessed directly

return array(
	'AP' => __( 'Andhra Pradesh', 'seur' ),
	'AR' => __( 'Arunachal Pradesh', 'seur' ),
	'AS' => __( 'Assam', 'seur' ),
	'BR' => __( 'Bihar', 'seur' ),
	'CT' => __( 'Chhattisgarh', 'seur' ),
	'GA' => __( 'Goa', 'seur' ),
	'GJ' => __( 'Gujarat', 'seur' ),
	'HR' => __( 'Haryana', 'seur' ),
	'HP' => __( 'Himachal Pradesh', 'seur' ),
	'JK' => __( 'Jammu and Kashmir', 'seur' ),
	'JH' => __( 'Jharkhand', 'seur' ),
	'KA' => __( 'Karnataka', 'seur' ),
	'KL' => __( 'Kerala', 'seur' ),
	'MP' => __( 'Madhya Pradesh', 'seur' ),
	'MH' => __( 'Maharashtra', 'seur' ),
	'MN' => __( 'Manipur', 'seur' ),
	'ML' => __( 'Meghalaya', 'seur' ),
	'MZ' => __( 'Mizoram', 'seur' ),
	'NL' => __( 'Nagaland', 'seur' ),
	'OR' => __( 'Orissa', 'seur' ),
	'PB' => __( 'Punjab', 'seur' ),
	'RJ' => __( 'Rajasthan', 'seur' ),
	'SK' => __( 'Sikkim', 'seur' ),
	'TN' => __( 'Tamil Nadu', 'seur' ),
	'TS' => __( 'Telangana', 'seur' ),
	'TR' => __( 'Tripura', 'seur' ),
	'UK' => __( 'Uttarakhand', 'seur' ),
	'UP' => __( 'Uttar Pradesh', 'seur' ),
	'WB' => __( 'West Bengal', 'seur' ),
	'AN' => __( 'Andaman and Nicobar Islands', 'seur' ),
	'CH' => __( 'Chandigarh', 'seur' ),
	'DN' => __( 'Dadar and Nagar Haveli', 'seur' ),
	'DD' => __( 'Daman and Diu', 'seur' ),
	'DL' => __( 'Delhi', 'seur' ),
	'LD' => __( 'Lakshadeep', 'seur' ),
	'PY' => __( 'Pondicherry (Puducherry)', 'seur' )
);
