<?php if ( ! defined( 'ABSPATH' ) ) exit; // Exit if accessed directly

return array(
	'KHZ' => __( 'Khuzestan  (خوزستان)', 'seur-oficial' ),
	'THR' => __( 'Tehran  (تهران)', 'seur-oficial' ),
	'ILM' => __( 'Ilaam (ایلام)', 'seur-oficial' ),
	'BHR' => __( 'Bushehr (بوشهر)', 'seur-oficial' ),
	'ADL' => __( 'Ardabil (اردبیل)', 'seur-oficial' ),
	'ESF' => __( 'Isfahan (اصفهان)', 'seur-oficial' ),
	'YZD' => __( 'Yazd (یزد)', 'seur-oficial' ),
	'KRH' => __( 'Kermanshah (کرمانشاه)', 'seur-oficial' ),
	'KRN' => __( 'Kerman (کرمان)', 'seur-oficial' ),
	'HDN' => __( 'Hamadan (همدان)', 'seur-oficial' ),
	'GZN' => __( 'Ghazvin (قزوین)', 'seur-oficial' ),
	'ZJN' => __( 'Zanjan (زنجان)', 'seur-oficial' ),
	'LRS' => __( 'Luristan (لرستان)', 'seur-oficial' ),
	'ABZ' => __( 'Alborz (البرز)', 'seur-oficial' ),
	'EAZ' => __( 'East Azarbaijan (آذربایجان شرقی)', 'seur-oficial' ),
	'WAZ' => __( 'West Azarbaijan (آذربایجان غربی)', 'seur-oficial' ),
	'CHB' => __( 'Chaharmahal and Bakhtiari (چهارمحال و بختیاری)', 'seur-oficial' ),
	'SKH' => __( 'South Khorasan (خراسان جنوبی)', 'seur-oficial' ),
	'RKH' => __( 'Razavi Khorasan (خراسان رضوی)', 'seur-oficial' ),
	'NKH' => __( 'North Khorasan (خراسان جنوبی)', 'seur-oficial' ),
	'SMN' => __( 'Semnan (سمنان)', 'seur-oficial' ),
	'FRS' => __( 'Fars (فارس)', 'seur-oficial' ),
	'QHM' => __( 'Qom (قم)', 'seur-oficial' ),
	'KRD' => __( 'Kurdistan / کردستان)', 'seur-oficial' ),
	'KBD' => __( 'Kohgiluyeh and BoyerAhmad (کهگیلوییه و بویراحمد)', 'seur-oficial' ),
	'GLS' => __( 'Golestan (گلستان)', 'seur-oficial' ),
	'GIL' => __( 'Gilan (گیلان)', 'seur-oficial' ),
	'MZN' => __( 'Mazandaran (مازندران)', 'seur-oficial' ),
	'MKZ' => __( 'Markazi (مرکزی)', 'seur-oficial' ),
	'HRZ' => __( 'Hormozgan (هرمزگان)', 'seur-oficial' ),
	'SBN' => __( 'Sistan and Baluchestan (سیستان و بلوچستان)', 'seur-oficial' )
);
