<?php if ( ! defined( 'ABSPATH' ) ) exit; // Exit if accessed directly

return array(
	'KHZ' => __( 'Khuzestan  (خوزستان)', SEUR_TEXTDOMAIN ),
	'THR' => __( 'Tehran  (تهران)', SEUR_TEXTDOMAIN ),
	'ILM' => __( 'Ilaam (ایلام)', SEUR_TEXTDOMAIN ),
	'BHR' => __( 'Bushehr (بوشهر)', SEUR_TEXTDOMAIN ),
	'ADL' => __( 'Ardabil (اردبیل)', SEUR_TEXTDOMAIN ),
	'ESF' => __( 'Isfahan (اصفهان)', SEUR_TEXTDOMAIN ),
	'YZD' => __( 'Yazd (یزد)', SEUR_TEXTDOMAIN ),
	'KRH' => __( 'Kermanshah (کرمانشاه)', SEUR_TEXTDOMAIN ),
	'KRN' => __( 'Kerman (کرمان)', SEUR_TEXTDOMAIN ),
	'HDN' => __( 'Hamadan (همدان)', SEUR_TEXTDOMAIN ),
	'GZN' => __( 'Ghazvin (قزوین)', SEUR_TEXTDOMAIN ),
	'ZJN' => __( 'Zanjan (زنجان)', SEUR_TEXTDOMAIN ),
	'LRS' => __( 'Luristan (لرستان)', SEUR_TEXTDOMAIN ),
	'ABZ' => __( 'Alborz (البرز)', SEUR_TEXTDOMAIN ),
	'EAZ' => __( 'East Azarbaijan (آذربایجان شرقی)', SEUR_TEXTDOMAIN ),
	'WAZ' => __( 'West Azarbaijan (آذربایجان غربی)', SEUR_TEXTDOMAIN ),
	'CHB' => __( 'Chaharmahal and Bakhtiari (چهارمحال و بختیاری)', SEUR_TEXTDOMAIN ),
	'SKH' => __( 'South Khorasan (خراسان جنوبی)', SEUR_TEXTDOMAIN ),
	'RKH' => __( 'Razavi Khorasan (خراسان رضوی)', SEUR_TEXTDOMAIN ),
	'NKH' => __( 'North Khorasan (خراسان جنوبی)', SEUR_TEXTDOMAIN ),
	'SMN' => __( 'Semnan (سمنان)', SEUR_TEXTDOMAIN ),
	'FRS' => __( 'Fars (فارس)', SEUR_TEXTDOMAIN ),
	'QHM' => __( 'Qom (قم)', SEUR_TEXTDOMAIN ),
	'KRD' => __( 'Kurdistan / کردستان)', SEUR_TEXTDOMAIN ),
	'KBD' => __( 'Kohgiluyeh and BoyerAhmad (کهگیلوییه و بویراحمد)', SEUR_TEXTDOMAIN ),
	'GLS' => __( 'Golestan (گلستان)', SEUR_TEXTDOMAIN ),
	'GIL' => __( 'Gilan (گیلان)', SEUR_TEXTDOMAIN ),
	'MZN' => __( 'Mazandaran (مازندران)', SEUR_TEXTDOMAIN ),
	'MKZ' => __( 'Markazi (مرکزی)', SEUR_TEXTDOMAIN ),
	'HRZ' => __( 'Hormozgan (هرمزگان)', SEUR_TEXTDOMAIN ),
	'SBN' => __( 'Sistan and Baluchestan (سیستان و بلوچستان)', SEUR_TEXTDOMAIN )
);
