<?php if ( ! defined( 'ABSPATH' ) ) exit; // Exit if accessed directly

return array(
	'Distrito Federal' 		=> __( 'Distrito Federal', SEUR_TEXTDOMAIN ),
	'Jalisco' 				=> __( 'Jalisco', SEUR_TEXTDOMAIN ),
	'Nuevo Leon' 			=> __( 'Nuevo León', SEUR_TEXTDOMAIN ),
	'Aguascalientes' 		=> __( 'Aguascalientes', SEUR_TEXTDOMAIN ),
	'Baja California' 		=> __( 'Baja California', SEUR_TEXTDOMAIN ),
	'Baja California Sur' 	=> __( 'Baja California Sur', SEUR_TEXTDOMAIN ),
	'Campeche' 				=> __( 'Campeche', SEUR_TEXTDOMAIN ),
	'Chiapas' 				=> __( 'Chiapas', SEUR_TEXTDOMAIN ),
	'Chihuahua' 			=> __( 'Chihuahua', SEUR_TEXTDOMAIN ),
	'Coahuila' 				=> __( 'Coahuila', SEUR_TEXTDOMAIN ),
	'Colima' 				=> __( 'Colima', SEUR_TEXTDOMAIN ),
	'Durango' 				=> __( 'Durango', SEUR_TEXTDOMAIN ),
	'Guanajuato' 			=> __( 'Guanajuato', SEUR_TEXTDOMAIN ),
	'Guerrero' 				=> __( 'Guerrero', SEUR_TEXTDOMAIN ),
	'Hidalgo' 				=> __( 'Hidalgo', SEUR_TEXTDOMAIN ),
	'Estado de Mexico' 		=> __( 'Edo. de México', SEUR_TEXTDOMAIN ),
	'Michoacan' 			=> __( 'Michoacán', SEUR_TEXTDOMAIN ),
	'Morelos' 				=> __( 'Morelos', SEUR_TEXTDOMAIN ),
	'Nayarit' 				=> __( 'Nayarit', SEUR_TEXTDOMAIN ),
	'Oaxaca' 				=> __( 'Oaxaca', SEUR_TEXTDOMAIN ),
	'Puebla' 				=> __( 'Puebla', SEUR_TEXTDOMAIN ),
	'Queretaro' 			=> __( 'Querétaro', SEUR_TEXTDOMAIN ),
	'Quintana Roo' 			=> __( 'Quintana Roo', SEUR_TEXTDOMAIN ),
	'San Luis Potosi' 		=> __( 'San Luis Potosí', SEUR_TEXTDOMAIN ),
	'Sinaloa' 				=> __( 'Sinaloa', SEUR_TEXTDOMAIN ),
	'Sonora' 				=> __( 'Sonora', SEUR_TEXTDOMAIN ),
	'Tabasco' 				=> __( 'Tabasco', SEUR_TEXTDOMAIN ),
	'Tamaulipas' 			=> __( 'Tamaulipas', SEUR_TEXTDOMAIN ),
	'Tlaxcala' 				=> __( 'Tlaxcala', SEUR_TEXTDOMAIN ),
	'Veracruz' 				=> __( 'Veracruz', SEUR_TEXTDOMAIN ),
	'Yucatan' 				=> __( 'Yucatán', SEUR_TEXTDOMAIN ),
	'Zacatecas' 			=> __( 'Zacatecas', SEUR_TEXTDOMAIN )
);
