<?php if ( ! defined( 'ABSPATH' ) ) exit; // Exit if accessed directly

return array(
	'Distrito Federal' 		=> __( 'Distrito Federal', 'seur-oficial' ),
	'Jalisco' 				=> __( 'Jalisco', 'seur-oficial' ),
	'Nuevo Leon' 			=> __( 'Nuevo León', 'seur-oficial' ),
	'Aguascalientes' 		=> __( 'Aguascalientes', 'seur-oficial' ),
	'Baja California' 		=> __( 'Baja California', 'seur-oficial' ),
	'Baja California Sur' 	=> __( 'Baja California Sur', 'seur-oficial' ),
	'Campeche' 				=> __( 'Campeche', 'seur-oficial' ),
	'Chiapas' 				=> __( 'Chiapas', 'seur-oficial' ),
	'Chihuahua' 			=> __( 'Chihuahua', 'seur-oficial' ),
	'Coahuila' 				=> __( 'Coahuila', 'seur-oficial' ),
	'Colima' 				=> __( 'Colima', 'seur-oficial' ),
	'Durango' 				=> __( 'Durango', 'seur-oficial' ),
	'Guanajuato' 			=> __( 'Guanajuato', 'seur-oficial' ),
	'Guerrero' 				=> __( 'Guerrero', 'seur-oficial' ),
	'Hidalgo' 				=> __( 'Hidalgo', 'seur-oficial' ),
	'Estado de Mexico' 		=> __( 'Edo. de México', 'seur-oficial' ),
	'Michoacan' 			=> __( 'Michoacán', 'seur-oficial' ),
	'Morelos' 				=> __( 'Morelos', 'seur-oficial' ),
	'Nayarit' 				=> __( 'Nayarit', 'seur-oficial' ),
	'Oaxaca' 				=> __( 'Oaxaca', 'seur-oficial' ),
	'Puebla' 				=> __( 'Puebla', 'seur-oficial' ),
	'Queretaro' 			=> __( 'Querétaro', 'seur-oficial' ),
	'Quintana Roo' 			=> __( 'Quintana Roo', 'seur-oficial' ),
	'San Luis Potosi' 		=> __( 'San Luis Potosí', 'seur-oficial' ),
	'Sinaloa' 				=> __( 'Sinaloa', 'seur-oficial' ),
	'Sonora' 				=> __( 'Sonora', 'seur-oficial' ),
	'Tabasco' 				=> __( 'Tabasco', 'seur-oficial' ),
	'Tamaulipas' 			=> __( 'Tamaulipas', 'seur-oficial' ),
	'Tlaxcala' 				=> __( 'Tlaxcala', 'seur-oficial' ),
	'Veracruz' 				=> __( 'Veracruz', 'seur-oficial' ),
	'Yucatan' 				=> __( 'Yucatán', 'seur-oficial' ),
	'Zacatecas' 			=> __( 'Zacatecas', 'seur-oficial' )
);
