<?php if ( ! defined( 'ABSPATH' ) ) exit; // Exit if accessed directly

return array(
	'CAL' => __( 'El Callao', 'seur' ),
	'LMA' => __( 'Municipalidad Metropolitana de Lima', 'seur' ),
	'AMA' => __( 'Amazonas', 'seur' ),
	'ANC' => __( 'Ancash', 'seur' ),
	'APU' => __( 'Apur&iacute;mac', 'seur' ),
	'ARE' => __( 'Arequipa', 'seur' ),
	'AYA' => __( 'Ayacucho', 'seur' ),
	'CAJ' => __( 'Cajamarca', 'seur' ),
	'CUS' => __( 'Cusco', 'seur' ),
	'HUV' => __( 'Huancavelica', 'seur' ),
	'HUC' => __( 'Hu&aacute;nuco', 'seur' ),
	'ICA' => __( 'Ica', 'seur' ),
	'JUN' => __( 'Jun&iacute;n', 'seur' ),
	'LAL' => __( 'La Libertad', 'seur' ),
	'LAM' => __( 'Lambayeque', 'seur' ),
	'LIM' => __( 'Lima', 'seur' ),
	'LOR' => __( 'Loreto', 'seur' ),
	'MDD' => __( 'Madre de Dios', 'seur' ),
	'MOQ' => __( 'Moquegua', 'seur' ),
	'PAS' => __( 'Pasco', 'seur' ),
	'PIU' => __( 'Piura', 'seur' ),
	'PUN' => __( 'Puno', 'seur' ),
	'SAM' => __( 'San Mart&iacute;n', 'seur' ),
	'TAC' => __( 'Tacna', 'seur' ),
	'TUM' => __( 'Tumbes', 'seur' ),
	'UCA' => __( 'Ucayali', 'seur' )
);
